force-app/main/default/objects/MonthlyPayment__c/MonthlyPayment__c.object-meta.xml
<CustomObject>
    <label>Monthly Payment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Monthly Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MonthlyPayment__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Monthly Payments</relationshipLabel>
    <relationshipName>Monthly_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MonthlyPayment__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Price Adjustment (%)</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/MonthlyPayment__c/fields/End_date__c.field-meta.xml
<CustomField>
    <fullName>End_date__c</fullName>
    <formula>End_Date_trigger__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/MonthlyPayment__c/fields/Monthly_Units__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Units__c</fullName>
    <formula>IF(
  OR(Access_Type__c = &quot;Periodic&quot;, Access_Type__c = &quot;Monthly&quot;, Access_Type__c = &quot;Rent&quot;),
  (DAY(End_date__c) - DAY(Start_date__c) + 1) / 
  DAY(
    DATE(
      YEAR(Start_date__c) + IF(MONTH(Start_date__c) = 12, 1, 0), 
      IF(MONTH(Start_date__c) = 12, 1, MONTH(Start_date__c) + 1), 
      1
    ) - 1
  ),
  1
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Units</label>
    <precision>18</precision>
    <scale>18</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MonthlyPayment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Monthly Payments</relationshipLabel>
    <relationshipName>MonthlyPaymentRecords</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MonthlyPayment__c/fields/OpportunityLineItem__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLineItem__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Monthly Payments</relationshipLabel>
    <relationshipName>Monthly_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MonthlyPayment__c/fields/OrderItem__c.field-meta.xml
<CustomField>
    <fullName>OrderItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OrderItem</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Monthly Payments</relationshipLabel>
    <relationshipName>Monthly_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MonthlyPayment__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <formula>IF( ISBLANK(OrderItem__c),  OpportunityLineItem__r.TotalPrice *  Monthly_Units__c,  OrderItem__r.UnitPrice * OrderItem__r.Quantity * Monthly_Units__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MonthlyPayment__c/fields/Products_Name__c.field-meta.xml
<CustomField>
    <fullName>Products_Name__c</fullName>
    <formula>IF( ISBLANK(OrderItem__c)  , OpportunityLineItem__r.PricebookEntry.Product2.Name,  OrderItem__r.PricebookEntry.Product2.Name )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Products Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MonthlyPayment__c/fields/Start_date__c.field-meta.xml
<CustomField>
    <fullName>Start_date__c</fullName>
    <formula>Stat_Date_Trigger__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Aggregated_List_Price_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Aggregated_List_Price_Adjustment__c</fullName>
    <description>Aggregates price adjustment from list price and not sale price</description>
    <label>Aggregated List Price Adjustment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Calculated_List_Price_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Calculated_List_Price_Adjustment__c</fullName>
    <formula>IF(
OR(ISPICKVAL(Access_Type__c, &quot;Periodic&quot;), ISPICKVAL(Access_Type__c, &quot;Rent&quot;)),
( Aggregated_List_Price_Adjustment__c / Period_In_Months__c) ,

IF(
ISPICKVAL(Access_Type__c, &quot;Monthly&quot;),
(Aggregated_List_Price_Adjustment__c / 24) ,

( Aggregated_List_Price_Adjustment__c / 1)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calculated List Price Adjustment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/End_date__c.field-meta.xml
<CustomField>
    <fullName>End_date__c</fullName>
    <label>End date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Aggregated_List_Price_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Aggregated_List_Price_Adjustment__c</fullName>
    <label>Aggregated List Price Adjustment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Calculated_List_Price_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>Calculated_List_Price_Adjustment__c</fullName>
    <formula>IF(
ISPICKVAL(Access_Type__c, &quot;Periodic&quot;),
( Aggregated_List_Price_Adjustment__c / Period_In_Months__c) ,

IF(
ISPICKVAL(Access_Type__c, &quot;Monthly&quot;),
(Aggregated_List_Price_Adjustment__c / 24) ,

( Aggregated_List_Price_Adjustment__c / 1)
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calculated List Price Adjustment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Package Items</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityService.cls
/** Commercial-package subset: monthly payment read for filter UI. */
public without sharing class OpportunityService {
  @AuraEnabled
  public static List<MonthlyPayment__c> getMonthlyPayments(
    String oppId,
    String contractId
  ) {
    try {
      String query =
        'SELECT Start_date__c, End_date__c, Price__c, Products_Name__c, Monthly_Units__c, ' +
        'Discount__c, Id, ' +
        'OpportunityLineItem__c, OpportunityLineItem__r.Name, ' +
        'OpportunityLineItem__r.Aggregated_List_Price_Adjustment__c, ' +
        'OpportunityLineItem__r.Calculated_List_Price_Adjustment__c, ' +
        'OrderItem__r.Calculated_List_Price_Adjustment__c, ' +
        'OrderItem__r.Aggregated_List_Price_Adjustment__c ' +
        'FROM MonthlyPayment__c ';

      List<String> filters = new List<String>();
      if (contractId != null) {
        filters.add('Contract__c = :contractId');
        filters.add('Products_Name__c != null');
      } else if (oppId != null) {
        filters.add('Opportunity__c = :oppId');
      }
      filters.add('Start_date__c != null');

      if (!filters.isEmpty()) {
        query += 'WHERE ' + String.join(filters, ' AND ');
      }
      query += ' ORDER BY Start_date__c ASC';
      return Database.query(query);
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
  }
}